# Generated by Django 5.2.14 on 2026-05-14 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_title', models.CharField(blank=True, max_length=255)),
                ('input_description', models.TextField(blank=True)),
                ('input_category', models.CharField(blank=True, max_length=255)),
                ('input_brand', models.CharField(blank=True, max_length=255)),
                ('input_model_name', models.CharField(blank=True, max_length=255)),
                ('input_original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('input_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('input_usage_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('input_user_condition', models.CharField(blank=True, max_length=32)),
                ('image_used', models.ImageField(blank=True, null=True, upload_to='ai_inputs/')),
                ('gemini_model_name', models.CharField(blank=True, max_length=128)),
                ('gemini_prompt', models.TextField(blank=True)),
                ('gemini_raw_response', models.JSONField(blank=True, default=dict)),
                ('predicted_condition_label', models.CharField(blank=True, max_length=32)),
                ('predicted_condition_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suggested_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_price_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('confidence_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_results', to='products.productlisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
