# Generated by Django 5.2.14 on 2026-05-14 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('storage', models.CharField(blank=True, max_length=64)),
                ('ram', models.CharField(blank=True, max_length=64)),
                ('processor', models.CharField(blank=True, max_length=128)),
                ('battery_health', models.CharField(blank=True, max_length=64)),
                ('screen_condition', models.CharField(blank=True, max_length=64)),
                ('body_condition', models.CharField(blank=True, max_length=64)),
                ('warranty_status', models.CharField(blank=True, max_length=128)),
                ('accessories_included', models.TextField(blank=True)),
                ('box_available', models.BooleanField(default=False)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PKR', max_length=8)),
                ('product_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('user_declared_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=16)),
                ('ai_condition_label', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('ai_condition_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_suggested_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_suggested_price_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_suggested_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_price_explanation', models.TextField(blank=True, null=True)),
                ('ai_confidence_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_warnings', models.JSONField(blank=True, null=True)),
                ('is_ai_evaluated', models.BooleanField(default=False)),
                ('ai_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('active', 'Active'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productlisting')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
